### ISSUE TITLE
值显示在更多地方

### ISSUE THREAD

**Issue by afc163** [shezhangzhang/antd-design-token#2]
- 色彩作为背景：https://marketplace.visualstudio.com/items?itemName=kamikillerto.vscode-colorize
- 值直接放在变量后面：https://marketplace.visualstudio.com/items?itemName=wix.vscode-import-cost
- 输入提示列表的后面：
<img width="711" alt="图片" src="https://user-images.githubusercontent.com/507615/178740020-dc04c526-1972-44fa-be63-b4cd4b603d2e.png">

**Comment by afc163** [comment]
https://marketplace.visualstudio.com/items?itemName=emanuelebartolesi.css-initial-style-value

**Comment by shezhangzhang** [comment]
好的，本周会陆续加上优化功能😄
